In [1]:
import torch
# 创建tensor
x = torch.tensor([1, 2, 3])  # 从列表创建
y = torch.zeros(3, 4)        # 创建3×4的全零tensor

In [2]:
x

tensor([1, 2, 3])

In [3]:
y

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
# 重要属性
print(tensor.shape)       # 形状，如(3, 4)
print(tensor.dtype)       # 数据类型，如torch.float32
print(tensor.device)      # 所在设备，如'cpu'或'cuda:0'
print(tensor.requires_grad)  # 是否需要梯度计算

NameError: name 'tensor' is not defined

In [ ]:
# 理解维度是关键
x = torch.randn(2, 3)     # 2行3列
x = x.view(6)             # 重塑为6元素向量
x = x.unsqueeze(0)        # 添加维度:[6] -> [1,6]
x

tensor([[-1.1865, -0.2113,  0.0925, -0.1814,  1.6727,  0.4736]])

In [11]:
x = x.transpose(0, 1)     # 转置维度
x

tensor([[-1.1865],
        [-0.2113],
        [ 0.0925],
        [-0.1814],
        [ 1.6727],
        [ 0.4736]])

In [12]:
# 基本运算
z = x + y                 # 元素级加法
z = torch.matmul(x, y)    # 矩阵乘法
z = x * y                 # 元素级乘法(哈达玛积)

RuntimeError: The size of tensor a (6) must match the size of tensor b (3) at non-singleton dimension 0

In [13]:
# 广播机制
small = torch.ones(3)
big = torch.ones(2, 3)
result = small + big      # small自动广播匹配big的形状

In [14]:
result

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [15]:
# 类似NumPy
first_row = tensor[0]        # 第一行
sub_matrix = tensor[0:2, 1:3]  # 子矩阵

NameError: name 'tensor' is not defined

In [16]:
# 梯度计算
x = torch.ones(2, 2, requires_grad=True)
y = x * 2
z = y.mean()
z.backward()                # 计算梯度
print(x.grad)               # 显示梯度

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
